version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookings_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  bookings:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/bookings_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  pgdata:
